@startuml
scale 0.1
skinparam dpi 400
class com.example.parsing.ParserClass {
+ {static} int parseInt(String)
+ {static} long parseLong(String)
+ {static} float parseFloat(String)
+ {static} double parseDouble(String)
+ {static} E parseEnum(String,Class<E>)
}

interface com.example.app.commandhandling.Command {
~ void execute()
}

class com.example.app.commandhandling.commands.ExecuteScriptCommand {
- {static} Deque<String> executingScripts
- MovieCollection collection
- String fileName
- CommandInvoker invoker
+ void execute()
}


class com.example.app.commandhandling.commands.AddCommand {
- MovieCollection collection
- Scanner scanner
- Boolean execute_script
+ void execute()
}


class com.example.validate.WeightValidator {
+ void validate(Float)
}

class com.example.validate.LengthValidator {
+ void validate(Integer)
}

enum com.example.service.enums.Country {
+  FRANCE
+  SPAIN
+  USA
+  CANADA
+  GERMANY
+  NORTH_KOREA
}

class com.example.app.commandhandling.commands.ReorderCommand {
- MovieCollection collection
+ void execute()
}


class com.example.validate.OscarsCountValidator {
+ void validate(Integer)
}

class com.example.app.commandhandling.commands.RemoveFirstProgram {
- MovieCollection collection
+ void execute()
}


class com.example.service.MovieCollection {
- List<Movie> movies
- LocalDateTime initializationDate
+ void add(Movie)
+ void update(long,Movie)
+ void removeById(long)
+ void clear()
+ void show()
+ void reorder()
+ void removeAt(int)
+ void removeFirst()
+ void sumOfLength()
+ void countByOperator(String)
+ void printDescendingOscarsCount()
+ void setMovies(LinkedList<Movie>)
+ int size()
+ void save(String)
+ Movie get(int)
}


class com.example.app.commandhandling.CommandInvoker {
- Map<String,Command> commands
+ void register(String,Command)
+ void execute(String)
+ void execute(Command)
}


class com.example.app.Program {
+ {static} void main(String[])
}

enum com.example.service.enums.MovieGenre {
+  COMEDY
+  MUSICAL
+  THRILLER
+  HORROR
+  ROMANTIC
+  CRIMINAL
+  SCIENTIFIC
+  WAR
}

class com.example.validate.MovieValidator {
- Validator<String> nameValidator
- Validator<Coordinates> cordinatesValidator
- Validator<Integer> oscarsCountValidator
- Validator<Integer> lengthValidator
+ void validate(Movie)
}


class com.example.validate.XValidator {
+ void validate(Double)
}

class com.example.app.commandhandling.commands.InfoCommand {
- MovieCollection collection
+ void execute()
}


class com.example.app.commandhandling.commands.HelpCommand {
+ void execute()
}

class com.example.app.commandhandling.CommandHandler {
+ {static} void handleCommand(String,MovieCollection,Scanner,CommandInvoker,Boolean)
}

class com.example.app.commandhandling.commands.ShowCommand {
- MovieCollection collection
+ void execute()
}


interface com.example.validate.Validator {
~ void validate(T)
}

class com.example.app.commandhandling.commands.UpdateCommand {
- MovieCollection collection
- Scanner scanner
- String command
- Boolean execute_script
+ void execute()
}


class com.example.validate.IdsValidator {
+ void validate(List<Movie>)
- void validateIdsExisted(List<Movie>)
- long validateNoDuplicates(List<Movie>)
- void updateIdGenerator(long)
}

class com.example.app.commandhandling.commands.CountByOperator {
- MovieCollection collection
- String operatorName
+ void execute()
}


class com.example.service.model.Movie {
- Long id
- String name
- Coordinates coordinates
- LocalDate creationDate
- int oscarsCount
- Integer length
- MovieGenre genre
- MpaaRating mpaaRating
- Person operator
- {static} Validator<String> nameValidator
- {static} Validator<Coordinates> coordinatesValidator
- {static} Validator<Integer> oscarsCountValidator
- {static} Validator<Integer> lengthValidator
+ void generateId()
+ void updateId(long)
+ void setName(String)
+ void setCoordinates(Coordinates)
+ void setOscarsCount(int)
+ void setLength(Integer)
+ int compareTo(Movie)
}


class com.example.validate.CoordinateValidator {
- Validator<Double> xValidate
- Validator<Long> yValidate
+ void validate(Coordinates)
}


class com.example.xml.MovieCollectionWrapper {
- List<Movie> movies
+ LinkedList<Movie> getMovies()
}


class com.example.parsing.ScanOperator {
- Scanner scanner
- Person operator
- Boolean execute_script
+ void setOperator()
}


class com.example.service.model.IdGenerator {
- {static} long nextId
+ {static} long getNextId()
+ {static} void reset(long)
}


class com.example.validate.HeightValidator {
+ void validate(Long)
}

class com.example.validate.NameValidator {
+ void validate(String)
}

class com.example.app.commandhandling.commands.ClearCommand {
- MovieCollection collection
+ void execute()
}


class com.example.app.commandhandling.commands.RemoveAtCommand {
- MovieCollection collection
- String command
+ void execute()
}


class com.example.service.model.Person {
- String name
- Long height
- float weight
- Color eyeColor
- Country nationality
- {static} Validator<String> nameValidator
- {static} Validator<Long> heightValidator
- {static} Validator<Float> weightValidator
+ void setName(String)
+ void setHeight(Long)
+ void setWeight(float)
}


enum com.example.service.enums.Color {
+  YELLOW
+  ORANGE
+  WHITE
+  BLACK
+  PURPLE
}

class com.example.app.commandhandling.commands.SaveCommand {
- MovieCollection collection
- String filePath
+ void execute()
}


class com.example.app.commandhandling.commands.ExitCommand {
+ void execute()
}

class com.example.app.commandhandling.commands.RemoveByIdCommand {
- MovieCollection collection
- String command
+ void execute()
}


class com.example.app.commandhandling.commands.PrintDescendingOscarsCountCommand {
- MovieCollection collection
+ void execute()
}


class com.example.xml.XMLHandler {
- String filePath
- {static} Validator<Movie> movieValidator
- {static} Validator<List<Movie>> idsValidator
+ void save(LinkedList<Movie>)
+ LinkedList<Movie> loadLocal()
- LinkedList<Movie> getMovies(BufferedReader)
}


class com.example.parsing.ScanMovie {
- Movie movie
- Coordinates coordinates
- Scanner scanner
- Boolean execute_script
+ void setName()
+ void setCoordinates()
+ void setOscarsCount()
+ void setLength()
+ void setGenre()
+ void setMpaaRating()
}


class com.example.validate.YValidator {
+ void validate(Long)
}

class com.example.service.model.Coordinates {
- double x
- Long y
- {static} Validator<Double> xValidator
- {static} Validator<Long> yValidator
+ void setX(double)
+ void setY(Long)
}


enum com.example.service.enums.MpaaRating {
+  G
+  R
+  PG_13
+  NC_17
}

class com.example.app.commandhandling.commands.SumOfLengthCommand {
- MovieCollection collection
+ void execute()
}




com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.ExecuteScriptCommand
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.AddCommand
com.example.validate.Validator <|.. com.example.validate.WeightValidator
com.example.validate.Validator <|.. com.example.validate.LengthValidator
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.ReorderCommand
com.example.validate.Validator <|.. com.example.validate.OscarsCountValidator
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.RemoveFirstProgram
com.example.validate.Validator <|.. com.example.validate.MovieValidator
com.example.validate.Validator <|.. com.example.validate.XValidator
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.InfoCommand
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.HelpCommand
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.ShowCommand
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.UpdateCommand
com.example.validate.Validator <|.. com.example.validate.IdsValidator
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.CountByOperator
com.example.service.model.Comparable <|.. com.example.service.model.Movie
com.example.parsing.ParserClass <|-- com.example.service.model.Movie
com.example.validate.Validator <|.. com.example.validate.CoordinateValidator
com.example.validate.Validator <|.. com.example.validate.HeightValidator
com.example.validate.Validator <|.. com.example.validate.NameValidator
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.ClearCommand
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.RemoveAtCommand
com.example.parsing.ParserClass <|-- com.example.service.model.Person
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.SaveCommand
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.ExitCommand
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.RemoveByIdCommand
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.PrintDescendingOscarsCountCommand
com.example.validate.Validator <|.. com.example.validate.YValidator
com.example.app.commandhandling.Command <|.. com.example.app.commandhandling.commands.SumOfLengthCommand
@enduml